### --------------------------------- ###
### --- Fix Macrophyte Taxontable --- ### 
### --------------------------------- ###

# -------------------------------
# date written: 03.03.22
# date last modified: 04.03.22
# Project: Evaluating European Broad River Types for Diatoms, Fish and Macrophytes
# Purpose: Clean taxontable for macrophytes and establish wish taxa to use.
# Notes: 
# -------------------------------

# setup -----------------------------------------------
options("box.path" = "~/R/box_modules")
library(data.table)
box::use(box/dfm)

# load data -------------------------------------------
tt <- readRDS("data/macrophytes/2022-02-24_taxontable_macrophytes.rds")

## drop placeholder row and subclass column
tt <- tt[species != "placeholder"]
tt[subclass == "", subclass := NA]

## Pinopsida (C) Conifers 
##  All extant conifers are perennial woody plants (wiki)
tt[class == "Pinopsida", taxon_state := "drop"]
tt[original_name == "Pseudanabaenoideae", c("species", "genus") := NA]
## Can not find this taxon anywhere, drop it 
tt[original_name == "Dichelymoides sp.", taxon_state := "drop"]
## Drop rows with missing entries. They will be added one by one with correct information below. 
tt <- tt[!original_name %in% c(
        "Agrostis sp.",
        "Gardamine pratensis",
        "Glyseria sp.",
        "Hydrocharis morsus.ranae",
        "Marsupella sp ",
        "Mycopus europeus",
        "Nymphaea ssp.candida.C.Presl.J.Persl.Korsh",
        "Petasites sp.ruttojuuri",
        "Ranunculus ssp.peltatus"
)]

## Ruttojuuri is a finnish common name for the genus of Petasites
tt <- dfm$append_to_tt(
        ori = "Petasites sp.ruttojuuri",
        fix = "Petasites",
        data_from = tt,
        data_to = tt
)
tt <- dfm$new_entry_nd(
        ori = "Agrostis sp.",
        spe = NA,
        gen =  "Agrostis",
        taxontable = tt
)
tt <- dfm$new_entry_nd(ori = "Ranunculus ssp.peltatus",
                       spe = "Ranunculus peltatus",
                       taxontable = tt)
tt <-
        dfm$new_entry_nd(ori = "Gardamine pratensis",
                         spe = "Cardamine pratensis",
                         taxontable = tt)
tt <-
        dfm$new_entry_nd("Glyseria sp.",
                         spe = NA,
                         gen = "Glyceria",
                         taxontable = tt)
tt <-
        dfm$new_entry_nd("Marsupella sp ",
                         spe = NA,
                         gen = "Marsupella",
                         taxontable = tt)
## Pteropsida is outdated and very high level. Drop
tt[original_name ==      "Pteropsida", taxon_state := "drop"] 

tt <-
        dfm$append_to_tt(
                ori = "Hydrocharis morsus.ranae",
                fix = "Hydrocharis morsus-ranae",
                data_from = tt,
                data_to = tt
        )
tt <-
        dfm$append_to_tt(
                ori = "Mycopus europeus",
                fix = "Lycopus europaeus",
                data_from = tt,
                data_to = tt
        )
tt <-
        dfm$append_to_tt(
                ori = "Nymphaea ssp.candida.C.Presl.J.Persl.Korsh",
                fix = "Nymphaea candida",
                data_from = tt,
                data_to = tt
        )
tt[original_name == "Glyceria aquatica", c("species", "genus") := .("Glyceria maxima", "Glyceria")]



## Acorales - sweet flag/ Kalmus - helophytes 
tt[order == "Acorales", taxon_state := "helophytes"]
tt[genus == "Abutilon", taxon_state := "drop"]
tt[genus == "Achillea", taxon_state := "drop"]
tt[genus == "Achnatherum", taxon_state := "drop"]
tt[genus == "Aconitum", taxon_state := "drop"]
tt[genus == "Adoxa", taxon_state := "drop"]
tt[genus == "Aegopodium", taxon_state := "drop"]
tt[order == "Sapindales", taxon_state := "drop"]
tt[genus == "Aethusa", taxon_state := "drop"]
tt[genus == "Agropyron", taxon_state := "drop"]
tt[genus == "Agrostis", taxon_state := "drop"]
tt[genus == "Ajuga", taxon_state := "drop"]
tt[genus == "Alcedo", taxon_state := "drop"]
tt[genus == "Alchemilla", taxon_state := "drop"]
tt[genus == "Alisma", taxon_state := "helophytes"]
tt[genus == "Alliaria", taxon_state := "drop"]
tt[genus == "Allium", taxon_state := "drop"]


tt[genus == "Alnus"             ,taxon_state := "drop"]
tt[genus == "Alopecurus"        ,taxon_state := "drop"]
tt[genus == "Althaea"           ,taxon_state := "drop"]
tt[genus == "Amaranthus"        ,taxon_state := "drop"]
tt[genus == "Amblystegium"      ,taxon_state := "moss"]
tt[genus == "Ambrosia"          ,taxon_state := "drop"]
tt[genus == "Amelanchier"       ,taxon_state := "drop"]
tt[genus == "Amorpha"           ,taxon_state := "drop"]
tt[genus == "Anabaena"          ,taxon_state := "cyanobacteria"]
tt[genus == "Anabaenopsis"      ,taxon_state := "cyanobacteria"]
tt[genus == "Anacamptis"        ,taxon_state := "drop"]
tt[genus == "Anemone"           ,taxon_state := "drop"]
tt[genus == "Aneura"            ,taxon_state := "jungermanniopsida"]
tt[genus == "Angelica"          ,taxon_state := "drop"]
tt[genus == "Ankistrodesmus"    ,taxon_state := "Chlorophyceae"]
tt[genus == "Anodonta"          ,taxon_state := "drop"]
tt[genus == "Anomodon"          ,taxon_state := "moss"]
tt[genus == "Anthoxanthum"      ,taxon_state := "drop"]
tt[genus == "Anthriscus"        ,taxon_state := "drop"]
tt[genus == "Aphanizomenon"     ,taxon_state := "cyanobacteria"]
tt[genus == "Aphanocapsa"       ,taxon_state := "cyanobacteria"]
tt[genus == "Aphanothece"       ,taxon_state := "cyanobacteria"]
tt[genus == "Apium"             ,taxon_state := "drop"]
tt[genus == "Aponogeton"        ,taxon_state := "hydrophytes"]
tt[genus == "Arctium"           ,taxon_state := "drop"]
tt[genus == "Aristolochia"      ,taxon_state := "drop"]
tt[genus == "Armoracia"         ,taxon_state := "drop"]
tt[genus == "Arrhenatherum"     ,taxon_state := "drop"]
tt[genus == "Artemisia"         ,taxon_state := "drop"]
tt[genus == "Arum"              ,taxon_state := "drop"]
tt[genus == "Arundo"            ,taxon_state := "drop"]
tt[genus == "Asplenium"         ,taxon_state := "drop"]
tt[genus == "Aster"             ,taxon_state := "drop"]
tt[genus == "Athyrium"          ,taxon_state := "drop"]
tt[genus == "Atrichum"          ,taxon_state := "moss"]
tt[genus == "Atriplex"          ,taxon_state := "drop"]

tt[genus == "Atropa"            , taxon_state := "drop"]
tt[genus == "Audouinella"       , taxon_state := "Rhodophyta"]
tt[genus == "Aulacomnium"       , taxon_state := "moss"]
tt[genus == "Aulacoseira"       , taxon_state := "diatom"]
tt[genus == "Azolla"            , taxon_state := "hydrophytes"]
tt[genus == "Baldellia"         , taxon_state := "hydrophytes"]
tt[genus == "Ballota"           , taxon_state := "drop"]
tt[genus == "Bangia"            , taxon_state := "Rhodophyta"]
tt[genus == "Barbarea"          , taxon_state := "drop"]
tt[genus == "Barbula"           , taxon_state := "moss"]
tt[genus == "Bartsia"           , taxon_state := "drop"]
tt[genus == "Batrachospermum"   , taxon_state := "Rhodophyta"]
tt[genus == "Beckmannia"        , taxon_state := "helophytes"]
tt[genus == "Bellis"            , taxon_state := "drop"]
tt[genus == "Bellium"           , taxon_state := "drop"]
tt[genus == "Berula"            , taxon_state := "drop"]
tt[genus == "Betula"            , taxon_state := "drop"]
tt[genus == "Bidens"            , taxon_state := "helophytes"]
tt[genus == "Bistorta"          , taxon_state := "drop"]
tt[genus == "Blindia"           , taxon_state := "moss"]
tt[genus == "Bolboschoenus"     , taxon_state := "helophytes"]
tt[genus == "Brachypodium"      , taxon_state := "drop"]
tt[genus == "Brachythecium"     , taxon_state := "moss"]
 
tt[phylum == "Bryophyta", taxon_state := "moss"]
tt[phylum == "Marchantiophyta", taxon_state := "liverwort"]
tt[kingdom %in% c("Animalia"), taxon_state := "drop"]
tt[phylum == "Cyanobacteria", taxon_state := "cyanobacteria"]
tt[kingdom == "Protozoa", taxon_state := "protozoa"]
tt[kingdom == "Fungi", taxon_state := "lichen"]
tt[class == "Bacillariophyceae", taxon_state := "diatoms"]
tt[class %in% c("Charophyceae", "Chlorophyceae"), taxon_state := "green_algae"]
tt[phylum %in% c("Charophyta"), taxon_state := "green_algae"]
tt[phylum %in% c("Rhodophyta"), taxon_state := "red_algae"]
tt[class %in% c("Phaeophyceae"), taxon_state := "brown_algae"]
tt[class %in% c("Xanthophyceae"), taxon_state := "yellow_green_algae"]
tt[class %in% c("Chrysophyceae"), taxon_state := "golden_algae"]
tt[class %in% c("Cryptophyceae"), taxon_state := "Cryptophyceae_algae"]
tt[class %in% c("Ulvophyceae"), taxon_state := "green_algae"]

tt[, unique(class)] |> sort()
tt[, unique(order)] |> sort()
tt[order %in% c("Vitales", "Fagales"), taxon_state := "drop"]
tt[, unique(genus)] |> sort()

tt[genus == "Ceratocapnos", sort(unique(species))]

tt[genus == "Brassica"        , taxon_state := "drop"]
tt[genus == "Briza"           , taxon_state := "drop"]
tt[genus == "Bromus"          , taxon_state := "drop"]
tt[genus == "Bryonia"         , taxon_state := "drop"]
tt[genus == "Butomus"         , taxon_state := "helophytes"]
tt[genus == "Cabomba"         , taxon_state := "hydrophytes"]
tt[genus == "Calamagrostis"   , taxon_state := "drop"]
tt[genus == "Calla"           , taxon_state := "helophytes"]
tt[genus == "Callitriche"     , taxon_state := "hydrophytes"]
tt[genus == "Calluna"         , taxon_state := "drop"]
tt[species == "Caltha palustris", taxon_state := "helophytes"]
tt[genus == "Calystegia"      , taxon_state := "drop"]
tt[genus == "Camelina"        , taxon_state := "drop"]
tt[genus == "Campanula"       , taxon_state := "drop"]
tt[genus == "Camphorosma"     , taxon_state := "drop"]
tt[genus == "Capsella"        , taxon_state := "drop"]
tt[genus == "Cardamine"       , taxon_state := "drop"]
tt[genus == "Carduus"         , taxon_state := "drop"]
tt[genus == "Carex"           , taxon_state := "helophytes"]
tt[genus == "Carpinus"        , taxon_state := "drop"]
tt[genus == "Carum"           , taxon_state := "drop"]
tt[genus == "Catabrosa"       , taxon_state := "helophytes"]
tt[genus == "Centaurea"       , taxon_state := "drop"]
tt[genus == "Centaurium"      , taxon_state := "drop"]
tt[genus == "Cerastium"       , taxon_state := "drop"]
tt[genus == "Ceratocapnos"    , taxon_state := "drop"]
tt[genus == "Ceratophyllum"   , taxon_state := "hydrophytes"]
tt[genus == "Chaerophyllum"   , taxon_state := "drop"]
tt[genus == "Chamaenerion"    , taxon_state := "drop"]
tt[genus == "Chelidonium"     , taxon_state := "drop"]
tt[genus == "Chenopodium"     , taxon_state := "drop"]
tt[genus == "Chrysosplenium"  , taxon_state := "drop"]
tt[genus == "Cicuta"          , taxon_state := "drop"]
tt[genus == "Circaea"         , taxon_state := "drop"]
tt[genus == "Cirsium"         , taxon_state := "drop"]
tt[genus == "Cladium"         , taxon_state := "drop"]
tt[genus == "Claytonia"       , taxon_state := "drop"]
tt[genus == "Clematis"        , taxon_state := "drop"]
tt[genus == "Comarum"         , taxon_state := "helophytes"]
tt[genus == "Conium"          , taxon_state := "drop"]
tt[genus == "Convallaria"     , taxon_state := "drop"]
tt[genus == "Convolvulus"     , taxon_state := "drop"]
tt[genus == "Cornus"          , taxon_state := "drop"]
tt[genus == "Corrigiola"      , taxon_state := "drop"]
tt[genus == "Corylus"         , taxon_state := "drop"]
tt[genus == "Cotula"          , taxon_state := "drop"]
tt[species == "Crassula helmsii", taxon_state := "helophytes"]
tt[genus == "Crataegus"       , taxon_state := "drop"]

tt[genus == "Crepis"          , taxon_state := "drop"]
tt[genus == "Cymbalaria"      , taxon_state := "drop"]
tt[genus == "Cynodon"         , taxon_state := "drop"]
tt[genus == "Cyperus"         , taxon_state := "helophytes"]
tt[genus == "Cystopteris"     , taxon_state := "drop"]
tt[genus == "Cytisus"         , taxon_state := "drop"]
tt[genus == "Dactylis"        , taxon_state := "drop"]
tt[genus == "Dactylorhiza"    , taxon_state := "helophytes"]
tt[genus == "Damasonium"      , taxon_state := "hydrophytes"]
tt[genus == "Danthonia"       , taxon_state := "drop"]
tt[genus == "Daucus"          , taxon_state := "drop"]
tt[genus == "Deschampsia"     , taxon_state := "drop"]
tt[genus == "Digitalis"       , taxon_state := "drop"]
tt[genus == "Digitaria"       , taxon_state := "drop"]
tt[genus == "Dipsacus"        , taxon_state := "drop"]
tt[genus == "Dittrichia"      , taxon_state := "drop"]
tt[genus == "Drosera"         , taxon_state := "helophytes"]
tt[genus == "Dryopteris"      , taxon_state := "drop"]
tt[genus == "Dysphania"       , taxon_state := "drop"]
tt[genus == "Echinochloa"     , taxon_state := "drop"]
tt[genus == "Echinocystis"    , taxon_state := "drop"]
tt[genus == "Echinops"        , taxon_state := "drop"]
tt[genus == "Egeria"          , taxon_state := "hydrophytes"]
tt[genus == "Eichhornia"      , taxon_state := "hydrophytes"]
tt[genus == "Elaeagnus"       , taxon_state := "drop"]
tt[genus == "Elatine"         , taxon_state := "hydrophytes"]
tt[genus == "Eleocharis"      , taxon_state := "helophytes"]
tt[genus == "Elodea"          , taxon_state := "hydrophytes"]
tt[genus == "Elymus"          , taxon_state := "drop"]
tt[genus == "Empetrum"        , taxon_state := "drop"]
tt[genus == "Epilobium"       , taxon_state := "drop"]
tt[species == "Epilobium palustre"       , taxon_state := "helophytes"]
tt[genus == "Epipactis"       , taxon_state := "drop"]
tt[species == "Epipactis palustris"       , taxon_state := "helophytes"]
tt[species == "Equisetum arvense"       , taxon_state := "drop"]
tt[species == "Equisetum fluviatile"       , taxon_state := "hydrophytes"]
tt[species == "Equisetum hyemale"       , taxon_state := "drop"]
tt[species == "Equisetum telmateia"       , taxon_state := "drop"]
tt[species == "Equisetum palustre"       , taxon_state := "drop"]
tt[species == "Equisetum ramosissimum"       , taxon_state := "drop"]
tt[species == "Equisetum telmateia"       , taxon_state := "drop"]
tt[species == "Equisetum variegatum"       , taxon_state := "drop"]
tt[species == "Equisetum litorale"       , taxon_state := "drop"]
tt[species == "Equisetum sylvaticum"       , taxon_state := "drop"]
tt[species == "Equisetum pratense"       , taxon_state := "drop"]
tt[genus == "Eragrostis"      , taxon_state := "drop"]
tt[genus == "Erica"           , taxon_state := "drop"]
tt[genus == "Erigeron"        , taxon_state := "drop"]
tt[genus == "Eriophorum"      , taxon_state := "drop"]
tt[genus == "Eryngium"        , taxon_state := "drop"]
tt[genus == "Erysimum"        , taxon_state := "drop"]
tt[genus == "Erythranthe"     , taxon_state := "drop"]
tt[genus == "Euonymus"        , taxon_state := "drop"]
tt[genus == "Eupatorium"      , taxon_state := "drop"]
tt[genus == "Euphorbia"       , taxon_state := "drop"]
tt[species == "Euphorbia palustris"       , taxon_state := "helophytes"]
tt[genus == "Euphrasia"       , taxon_state := "drop"]
tt[genus == "Euthamia"        , taxon_state := "drop"]
tt[genus == "Fagus"           , taxon_state := "drop"]
tt[genus == "Fallopia"        , taxon_state := "drop"]
tt[genus == "Festuca"         , taxon_state := "drop"]
tt[genus == "Ficaria"         , taxon_state := "drop"]
tt[genus == "Filipendula"     , taxon_state := "drop"]
tt[genus == "Fragaria"        , taxon_state := "drop"]

tt[genus =="Frangula"        , taxon_state := "drop"]
tt[genus =="Fraxinus"        , taxon_state := "drop"]
tt[genus =="Galega"          , taxon_state := "drop"]
tt[genus =="Galeopsis"       , taxon_state := "drop"]
tt[genus =="Galinsoga"       , taxon_state := "drop"]
tt[genus =="Galium"          , taxon_state := "drop"]
tt[species == "Galium palustre"          , taxon_state := "helophytes"]
tt[genus =="Genista"         , taxon_state := "drop"]
tt[genus =="Gentiana"        , taxon_state := "drop"]
tt[genus =="Geranium"        , taxon_state := "drop"]
tt[species =="Geranium palustre"        , taxon_state := "helophytes"]
tt[genus =="Geum"            , taxon_state := "drop"]
tt[genus =="Glechoma"        , taxon_state := "drop"]
tt[genus =="Glyceria"        , taxon_state := "drop"]
tt[genus =="Glyceria maxima"        , taxon_state := "hydrophytes"]
tt[genus =="Glyceria fluitans"        , taxon_state := "hydrophytes"]
tt[genus =="Gnaphalium"      , taxon_state := "drop"]
tt[genus =="Gratiola"        , taxon_state := "drop"]
tt[genus =="Groenlandia"     , taxon_state := "hydrophytes"]
tt[genus =="Gunnera"         , taxon_state := "drop"]
tt[genus =="Gymnocarpium"    , taxon_state := "drop"]
tt[genus =="Hedera"          , taxon_state := "drop"]
tt[genus =="Helianthus"      , taxon_state := "drop"]
tt[species =="Helosciadium inundatum"    , taxon_state := "hydrophytes"]
tt[species =="Helosciadium nodiflorum"    , taxon_state := "drop"]
tt[species =="Helosciadium repens"    , taxon_state := "helophytes"]
tt[genus =="Heracleum"       , taxon_state := "drop"]
tt[genus =="Hesperis"        , taxon_state := "drop"]
tt[genus =="Hieracium"       , taxon_state := "drop"]
tt[genus =="Hippuris"        , taxon_state := "helophytes"]
tt[genus =="Holcus"          , taxon_state := "drop"]
tt[genus =="Hordelymus"      , taxon_state := "drop"]
tt[genus =="Hordeum"         , taxon_state := "drop"]
tt[genus =="Hottonia"        , taxon_state := "hydrophytes"]
tt[genus =="Humulus"         , taxon_state := "drop"]
tt[genus =="Hydrocharis"     , taxon_state := "hydrophytes"]
tt[genus =="Hydrocotyle"     , taxon_state := "hydrophytes"]
tt[genus =="Hygrophila"      , taxon_state := "hydrophytes"]
tt[genus =="Hypericum"       , taxon_state := "drop"]
tt[genus =="Hypochaeris"     , taxon_state := "drop"]
tt[genus =="Ilex"            , taxon_state := "drop"]
tt[genus =="Illecebrum"      , taxon_state := "drop"]
tt[genus =="Impatiens"       , taxon_state := "drop"]
tt[genus =="Imperatoria"     , taxon_state := "drop"]
tt[genus =="Inula"           , taxon_state := "drop"]
tt[genus =="Iris"            , taxon_state := "drop"]
tt[genus =="Isoetes"         , taxon_state := "hydrophytes"]
tt[genus =="Isolepis"        , taxon_state := "drop"]
tt[genus =="Jacobaea"        , taxon_state := "drop"]
tt[genus =="Jasione"         , taxon_state := "drop"]
tt[genus =="Juglans"         , taxon_state := "drop"]
tt[genus =="Juncus"          , taxon_state := "helophytes"]
tt[genus =="Kedrostis"       , taxon_state := "drop"]
tt[genus =="Knautia"         , taxon_state := "drop"]
tt[genus =="Lactuca"         , taxon_state := "drop"]
tt[genus =="Lagarosiphon"    , taxon_state := "hydrophytes"]
tt[genus =="Lamium"          , taxon_state := "drop"]
tt[genus =="Lapsana"         , taxon_state := "drop"]
tt[genus =="Lathyrus"        , taxon_state := "drop"]
tt[genus =="Leersia"         , taxon_state := "hydrophytes"]
tt[genus =="Lemna"           , taxon_state := "hydrophytes"]
tt[genus =="Leontodon"       , taxon_state := "drop"]
tt[genus =="Lepidium"        , taxon_state := "drop"]
tt[genus =="Leucanthemum"    , taxon_state := "drop"]
tt[genus =="Leucojum"        , taxon_state := "drop"]
tt[genus =="Ligustrum"       , taxon_state := "drop"]
tt[genus =="Limonium"        , taxon_state := "drop"]
tt[genus =="Linaria"         , taxon_state := "drop"]
tt[genus =="Lindernia"       , taxon_state := "drop"]
tt[genus =="Linnaea"         , taxon_state := "drop"]
tt[genus =="Linum"           , taxon_state := "drop"]
tt[genus =="Lipandra"        , taxon_state := "drop"]
tt[genus =="Littorella"      , taxon_state := "hydrophytes"]
tt[genus =="Lobelia"         , taxon_state := "drop"]
tt[genus =="Lolium"          , taxon_state := "drop"]
tt[genus =="Lonicera"        , taxon_state := "drop"]
tt[genus =="Lotus"           , taxon_state := "drop"]
tt[genus =="Ludwigia"        , taxon_state := "helophytes"]
tt[genus =="Lunaria"         , taxon_state := "drop"]
tt[genus =="Luronium"        , taxon_state := "hydrophytes"]
tt[genus =="Luzula"          , taxon_state := "drop"]
tt[genus =="Lycopodiella"    , taxon_state := "drop"]
tt[genus =="Lycopus"         , taxon_state := "drop"]
tt[genus =="Lysichiton"      , taxon_state := "drop"]
tt[genus =="Lysimachia"      , taxon_state := "drop"]
tt[genus =="Lythrum"         , taxon_state := "drop"]
tt[genus =="Maianthemum"     , taxon_state := "drop"]
tt[genus =="Malva"           , taxon_state := "drop"]
tt[genus =="Marsilea"        , taxon_state := "hydrophytes"]
tt[genus =="Matricaria"      , taxon_state := "drop"]
tt[genus =="Medicago"        , taxon_state := "drop"]
tt[genus =="Melica"          , taxon_state := "drop"]
tt[genus =="Melilotus"       , taxon_state := "drop"]
tt[genus =="Mentha"          , taxon_state := "drop"]
tt[genus =="Menyanthes"      , taxon_state := "hydrophytes"]
tt[genus =="Mercurialis"     , taxon_state := "drop"]
tt[genus =="Milium"          , taxon_state := "drop"]
tt[genus =="Moehringia"      , taxon_state := "drop"]
tt[genus =="Molinia"         , taxon_state := "drop"]
tt[genus =="Montia"          , taxon_state := "hydrophytes"]
tt[genus =="Morus"           , taxon_state := "drop"]
tt[genus =="Mycelis"         , taxon_state := "drop"]
tt[genus =="Myosotis"        , taxon_state := "drop"]
tt[genus =="Myosoton"        , taxon_state := "drop"]
tt[genus =="Myrica"          , taxon_state := "drop"]
tt[genus =="Myriophyllum"    , taxon_state := "hydrophytes"]
tt[genus =="Najas"           , taxon_state := "hydrophytes"]
tt[genus =="Nardus"          , taxon_state := "drop"]
tt[genus =="Narthecium"      , taxon_state := "drop"]
tt[genus =="Nasturtium"      , taxon_state := "helophytes"]
tt[genus =="Neottia"         , taxon_state := "drop"]
tt[genus =="Nuphar"          , taxon_state := "hydrophytes"]
tt[genus =="Nymphaea"        , taxon_state := "hydrophytes"]
tt[genus =="Nymphoides"      , taxon_state := "hydrophytes"]
tt[genus =="Odontites"       , taxon_state := "drop"]
tt[species == "Oenanthe aquatica", taxon_state := "hydrophytes"]
tt[species == "Oenanthe crocata", taxon_state := "drop"]
tt[species == "Oenanthe fistulosa", taxon_state := "hydrophytes"]
tt[species == "Oenanthe fluviatilis", taxon_state := "hydrophytes"]
tt[species == "Oenanthe silaifolia", taxon_state := "drop"]
tt[species == "Oenanthe banatica", taxon_state := "drop"]


tt[genus =="Oenothera"       , taxon_state := "drop"]
tt[genus =="Omphalodes"      , taxon_state := "drop"]
tt[genus =="Osmunda"         , taxon_state := "drop"]
tt[genus =="Oxalis"          , taxon_state := "drop"]
tt[genus =="Panicum"         , taxon_state := "drop"]
tt[genus =="Papaver"         , taxon_state := "drop"]
tt[genus =="Parentucellia"   , taxon_state := "drop"]
tt[genus =="Parietaria"      , taxon_state := "drop"]
tt[genus =="Paris"           , taxon_state := "drop"]
tt[genus =="Parnassia"       , taxon_state := "drop"]
tt[genus =="Parthenocissus"  , taxon_state := "drop"]
tt[genus =="Paspalum"        , taxon_state := "drop"]
tt[genus =="Pastinaca"       , taxon_state := "drop"]
tt[genus =="Pedicularis"     , taxon_state := "drop"]
tt[genus =="Pentanema"       , taxon_state := "drop"]
tt[genus =="Persicaria"      , taxon_state := "drop"]
tt[species == "Persicaria hydropiper", taxon_state := "helophytes"]
tt[species == "Persicaria amphibia"        , taxon_state := "hydrophytes"]
tt[species == "Persicaria lapathifolia"    , taxon_state := "drop"]
tt[species == "Persicaria maculosa"       , taxon_state := "drop"]
tt[species == "Persicaria minor", taxon_state := "drop"]
tt[species == "Persicaria mitis"           , taxon_state := "drop"]
tt[species == "Persicaria hydropiperoides" , taxon_state := "hydrophytes"]
tt[species == "Persicaria bistorta"       , taxon_state := "drop"]
tt[species == "Persicaria laxiflora"  , taxon_state := "drop"]
tt[genus =="Petasites"       , taxon_state := "drop"]
tt[genus =="Peucedanum"      , taxon_state := "drop"]
tt[genus =="Phalaris"        , taxon_state := "drop"]
tt[genus =="Phegopteris"     , taxon_state := "drop"]
tt[genus =="Phleum"          , taxon_state := "drop"]
tt[genus =="Phragmites"       , taxon_state := "helophytes"]
tt[genus =="Phyllitis"       ,taxon_state := "drop"]
tt[genus =="Picris"          , taxon_state := "drop"]
tt[genus =="Pilularia"       , taxon_state := "hydrophytes"]
tt[genus =="Pinguicula"      , taxon_state := "drop"]
tt[genus =="Pistia"          , taxon_state := "hydrophytes"]
tt[genus =="Plantago"        , taxon_state := "drop"]
tt[genus =="Poa"             , taxon_state := "drop"]
tt[genus =="Polygonatum"     , taxon_state := "drop"]
tt[genus =="Polygonum"       , taxon_state := "drop"]
tt[genus =="Polypodium"      , taxon_state := "drop"]
tt[genus =="Polypogon"       , taxon_state := "drop"]
tt[genus =="Pontederia"      , taxon_state := "hydrophytes"]
tt[genus =="Populus"         , taxon_state := "drop"]
tt[genus =="Portulaca"       , taxon_state := "drop"]
tt[genus =="Potamogeton"     , taxon_state := "hydrophytes"]
tt[genus =="Potentilla"      , taxon_state := "drop"]
tt[genus =="Primula"         , taxon_state := "drop"]
tt[genus =="Prunella"        , taxon_state := "drop"]
tt[genus =="Prunus"          , taxon_state := "drop"]
tt[genus =="Pteridium"       , taxon_state := "drop"]
tt[genus =="Puccinellia"     , taxon_state := "drop"]
tt[genus =="Pulicaria"       , taxon_state := "drop"]
tt[genus =="Pulmonaria"      , taxon_state := "drop"]
tt[genus =="Quercus"         , taxon_state := "drop"]
tt[genus =="Rabelera"        , taxon_state := "drop"]
tt[genus =="Ranunculus"      , taxon_state := "drop"]
tt[species =="Ranunculus repens"                    , taxon_state := "drop"]
tt[species =="Ranunculus aconitifolius"             , taxon_state := "drop"]
tt[species =="Ranunculus aquatilis"                 , taxon_state := "hydrophytes"]
tt[species =="Ranunculus batrachioides"             , taxon_state := "drop"]
tt[species =="Ranunculus bulbosus"                  , taxon_state := "drop"]
tt[species =="Ranunculus circinatus"                , taxon_state := "hydrophytes"]
tt[species =="Ranunculus flammula"                  , taxon_state := "drop"]
tt[species =="Ranunculus fluitans"                  , taxon_state := "hydrophytes"]
tt[species =="Ranunculus hederaceus"                , taxon_state := "hydrophytes"]
tt[species =="Ranunculus lingua"                    , taxon_state := "drop"]
tt[species =="Ranunculus omiophyllus"               , taxon_state := "hydrophytes"]
tt[species =="Ranunculus ophioglossifolius"         , taxon_state := "drop"]
tt[species =="Ranunculus peltatus"                  , taxon_state := "hydrophytes"]
tt[species =="Ranunculus penicillatus"              , taxon_state := "hydrophytes"]
tt[species =="Ranunculus sardous"                   , taxon_state := "drop"]
tt[species =="Ranunculus sceleratus"                , taxon_state := "drop"]
tt[species =="Ranunculus trichophyllus"             , taxon_state := "hydrophytes"]
tt[species =="Ranunculus tripartitus"               , taxon_state := "hydrophytes"]
tt[species =="Ranunculus fluitans x trichophyllus"  , taxon_state := "hydrophytes"]
tt[species =="Ranunculus reptans"                   , taxon_state := "hydrophytes"]
tt[species =="Ranunculus circinatus x trichophyllus", taxon_state := "hydrophytes"]
tt[species =="Ranunculus acris"                     , taxon_state := "drop"]
tt[species =="Ranunculus lanuginosus"               , taxon_state := "drop"]
tt[species =="Ranunculus auricomus"                 , taxon_state := "drop"]
tt[species =="Ranunculus rionii"                    , taxon_state := "hydrophytes"]
tt[species =="Ranunculus ololeucos"                 , taxon_state := "hydrophytes"]
tt[species =="Ranunculus confervoides × peltatus"   , taxon_state := "hydrophytes"]

tt[genus =="Reynoutria"      , taxon_state := "drop"]
tt[genus =="Rhamnus"         , taxon_state := "drop"]
tt[genus =="Rhinanthus"      , taxon_state := "drop"]
tt[genus =="Rhynchospora"    , taxon_state := "drop"]
tt[genus =="Ribes"           , taxon_state := "drop"]
tt[genus =="Robinia"         , taxon_state := "drop"]
tt[genus =="Rorippa"         , taxon_state := "hydrophytes"]
tt[genus =="Rosa"            , taxon_state := "drop"]
tt[genus =="Rubus"           , taxon_state := "drop"]
tt[genus =="Rumex"           , taxon_state := "drop"]
tt[genus =="Ruppia"          , taxon_state := "hydrophytes"]
tt[genus =="Sagina"          , taxon_state := "drop"]
tt[genus =="Sagittaria"      , taxon_state := "hydrophytes"]
tt[genus =="Salicornia"      , taxon_state := "drop"]
tt[genus =="Salix"           , taxon_state := "drop"]
tt[genus =="Salvia"          , taxon_state := "drop"]
tt[genus =="Salvinia"        , taxon_state := "hydrophytes"]
tt[genus =="Sambucus"        , taxon_state := "drop"]
tt[genus =="Samolus"         , taxon_state := "drop"]
tt[genus =="Sanguisorba"     , taxon_state := "drop"]
tt[genus =="Saxifraga"       , taxon_state := "drop"]
tt[genus =="Schoenoplectus"   , taxon_state := "helophytes"]
tt[genus =="Scirpoides"      , taxon_state := "drop"]
tt[genus =="Scirpus"         , taxon_state := "drop"]
tt[genus =="Scolochloa"      , taxon_state := "drop"]
tt[genus =="Scrophularia"    , taxon_state := "drop"]
tt[genus =="Scutellaria"     , taxon_state := "drop"]
tt[genus =="Sedum"           , taxon_state := "drop"]
tt[genus =="Selaginella"     , taxon_state := "drop"]
tt[genus =="Selinum"         , taxon_state := "drop"]
tt[genus =="Senecio"         , taxon_state := "drop"]
tt[genus =="Setaria"         , taxon_state := "drop"]
tt[genus =="Silene"          , taxon_state := "drop"]
tt[genus =="Sinapis"         , taxon_state := "drop"]
tt[genus =="Sisymbrium"      , taxon_state := "drop"]
tt[genus =="Sium"            , taxon_state := "hydrophytes"]
tt[genus =="Smyrnium"        , taxon_state := "drop"]
tt[genus =="Solanum"         , taxon_state := "drop"]
tt[genus =="Soleirolia"      , taxon_state := "drop"]
tt[genus =="Solidago"        , taxon_state := "drop"]
tt[genus =="Sonchus"         , taxon_state := "drop"]
tt[genus =="Sorbus"          , taxon_state := "drop"]
tt[genus =="Sparganium"       , taxon_state := "helophytes"]
tt[genus =="Spergula"        , taxon_state := "drop"]
tt[genus =="Spergularia"     , taxon_state := "drop"]
tt[genus =="Spiraea"         , taxon_state := "drop"]
tt[genus =="Spiranthes"      , taxon_state := "drop"]
tt[genus =="Spirodela"       , taxon_state := "hydrophytes"]
tt[genus =="Sporobolus"      , taxon_state := "drop"]
tt[genus =="Stachys"         , taxon_state := "drop"]
tt[genus =="Stellaria"       , taxon_state := "drop"]
tt[genus =="Stratiotes"      , taxon_state := "hydrophytes"]
tt[genus =="Stuckenia"       , taxon_state := "hydrophytes"]
tt[genus =="Subularia"       , taxon_state := "hydrophytes"]
tt[genus =="Succisa"         , taxon_state := "drop"]
tt[genus =="Symphoricarpos"  , taxon_state := "drop"]
tt[genus =="Symphyotrichum"  , taxon_state := "drop"]
tt[genus =="Symphytum"       , taxon_state := "drop"]
tt[genus =="Tanacetum"       , taxon_state := "drop"]
tt[genus =="Taraxacum"       , taxon_state := "drop"]
tt[genus =="Tephroseris"     , taxon_state := "drop"]
tt[genus =="Teucrium"        , taxon_state := "drop"]
tt[genus =="Thalictrum"      , taxon_state := "drop"]
tt[genus =="Thelypteris"     , taxon_state := "drop"]
tt[genus =="Thlaspi"         , taxon_state := "drop"]
tt[genus =="Thysselinum"     , taxon_state := "drop"]
tt[genus =="Tilia"           , taxon_state := "drop"]
tt[genus =="Torilis"         , taxon_state := "drop"]
tt[genus =="Tradescantia"    , taxon_state := "drop"]
tt[genus =="Trapa"           , taxon_state := "drop"]
tt[genus =="Trichophorum"    , taxon_state := "drop"]
tt[genus =="Trifolium"       , taxon_state := "drop"]
tt[genus =="Triglochin"      , taxon_state := "helophytes"]
tt[genus =="Tripleurospermum", taxon_state := "drop"]
tt[genus =="Tripolium"       , taxon_state := "drop"]
tt[genus =="Trollius"        , taxon_state := "drop"]
tt[genus =="Tussilago"       , taxon_state := "drop"]
tt[genus =="Typha"           , taxon_state := "helophytes"]
tt[genus =="Ulmus"           , taxon_state := "drop"]
tt[genus =="Urtica"          , taxon_state := "drop"]
tt[genus =="Utricularia"     , taxon_state := "helophytes"]
tt[genus =="Vaccinium"       , taxon_state := "drop"]
tt[genus =="Valeriana"       , taxon_state := "drop"]
tt[genus =="Vallisneria"     , taxon_state := "hydrophytes"]
tt[genus =="Veratrum"        , taxon_state := "drop"]
tt[genus =="Verbena"         , taxon_state := "drop"]
tt[genus =="Veronica"        , taxon_state := "drop"]
tt[genus =="Viburnum"        , taxon_state := "drop"]
tt[genus =="Vicia"           , taxon_state := "drop"]
tt[genus =="Vinca"           , taxon_state := "drop"]
tt[genus =="Viola"           , taxon_state := "drop"]
tt[genus =="Vitis"           , taxon_state := "drop"]
tt[genus =="Wahlenbergia"    , taxon_state := "drop"]
tt[genus =="Wolffia"         , taxon_state := "hydrophytes"]
tt[genus =="Xanthium"        , taxon_state := "drop"]
tt[genus =="Zannichellia"    , taxon_state := "hydrophytes"]
tt[genus =="Zantedeschia"  , taxon_state := "drop"]


tt[,unique(taxon_state)]

saveRDS(tt, paste0("data/macrophytes/", Sys.Date(), "_taxontable_macrophytes.rds"))
